resources:
- deployment.yaml
- service.yaml
- route.yaml
- infinispan.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:488fbe0b7a17486e10b1c60bf2393e19d76301fceb50dbf38284575da012488d
  name: quay.io/gtavares_pessoal/quinoa-wind-turbine
