resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:3b9e38a9a7527160a7290fde62d7f7012d3ede70dc982eab191e24770c048141
  name: quay.io/gtavares_pessoal/quinoa-wind-turbine
