resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:08df0ca76b1f99e6800c0c0708b2445508059451fc645682cd4e1438eac7d3c0
  name: quay.io/gtavares_pessoal/quinoa-wind-turbine
