resources:
- deployment.yaml
- service.yaml
- route.yaml
- infinispan.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:5c0c88b09da88368d3d3abd743ec9290f47e0978a0fecca72bd867f3c9419a59
  name: quay.io/gtavares_pessoal/quinoa-wind-turbine
