resources:
- deployment.yaml
- service.yaml
- route.yaml
- infinispan.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:8d684fd13e412881b203fe71852f39382744532b725b27e4c17bfbcb54e30064
  name: quay.io/gtavares_pessoal/quinoa-wind-turbine
