resources:
- deployment.yaml
- service.yaml
- route.yaml
- infinispan.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:7ab8cabc8ec7dcef4f6902e671a83dd37a94380cac7d5e319be7f09f52073d4e
  name: quay.io/gtavares_pessoal/quinoa-wind-turbine
