resources:
- deployment.yaml
- service.yaml
- route.yaml
- infinispan.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:c7735e58a909ce548a98ce167ff8ebfcca4a55d32c0c7f190d6bb7aaf63cd9eb
  name: quay.io/gtavares_pessoal/quinoa-wind-turbine
- digest: sha256:52e05873c7bd3689a38ca761e5bb41c19c087c58a81c3341b4e0a287c10d8740
  name: quay.io/gtavares_pessoals/quinoa-wind-turbine
- digest: sha256:637371bd10f05735fd77d6109e46a863455f5f57392cd070a472e9c2a07fc4c3
  name: quay.io/rhdevelopers/quinoa-wind-turbine
