resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:3f8df9840bbe6bb30a8fe9c47d158579f03fcd66de4ce7fbdccae8e216300156
  name: quay.io/gtavares_pessoal/quinoa-wind-turbine
