resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:51a610492bc2b15a621fd810ca4935deb164bda398da44bcc19c2c7d2ff3abef
  name: quay.io/gtavares_pessoal/quinoa-wind-turbine
