resources:
- deployment.yaml
- service.yaml
- route.yaml
- infinispan.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:b2c97a07db9d863335b619387138e327268f7261c93885a8952a25998a456135
  name: quay.io/gtavares_pessoal/quinoa-wind-turbine
