resources:
- deployment.yaml
- service.yaml
- route.yaml
- infinispan.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:1db42398ec816bea5f31e8cfec8da2f68d7ee126f44d143ee6f68c69a7ea1a5f
  name: quay.io/gtavares_pessoal/quinoa-wind-turbine
