resources:
- deployment.yaml
- service.yaml
- route.yaml
- infinispan.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:199c6dba75d227eb86edc0abb17b18768bd35fce2c00ee95d087971f0fc0dafb
  name: quay.io/gtavares_pessoal/quinoa-wind-turbine
