resources:
- deployment.yaml
- service.yaml
- route.yaml
- infinispan.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:db344715e00e97b054486bd9f681e1a92016705d21015658ae487f60b6d9c419
  name: quay.io/gtavares_pessoal/quinoa-wind-turbine
